title: OS2BorgerPC dokumentationssite
description: Dokumentation af administrationssites, images og scripts.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections:
  pages:
    permalink: "/:collection/:path/"
    output: true
  scripts:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    pages:
      name: Sider
      nav_fold: true
    scripts:
      name: Scripts
      nav_fold: false
