title: OS2BorgerPC dokumentationssite
description: Dokumentation af administrationssites, images og scripts.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  scripts:
    output: true
    permalink: /:collection/:path/
