blank_issues_enabled: false

issue_templates:
  - name: Fejl
    description: Systemet virker ikke som det plejer. Der er noget galt.
    labels: [bug]
  - name: Udviklingsønske
    description: Foreslå ny funktionalitet.
    labels: [enhancement]

